In [1]:
import numpy as np

In [2]:
np.array ([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
# List trong Python: các phần tử gồm kiểu Int và Float
[3.14, 5, 6, 7]

[3.14, 5, 6, 7]

In [4]:
# Numpy chuyển tất cả các phần tử về kiểu Float
np.array ([3.14, 5, 6, 7])

array([3.14, 5.  , 6.  , 7.  ])

In [5]:
# Cụ thể hóa kiểu dữ liệu mảng là kiểu Float 32 bit
np.array ([10, 11, 12, 13], dtype = 'float32')

array([10., 11., 12., 13.], dtype=float32)

In [6]:
a1 = np.array ([1, 2, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a2.shape

(4, 3)

In [12]:
a2.ndim

2

In [13]:
a2.dtype

dtype('int32')

In [14]:
a2 = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12]])
a2.size

12

In [17]:
np.zeros ([3, 6], dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
np.ones ([2, 4], dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.arange (0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.full((2,3), 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
np.linspace (0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [31]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [35]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [36]:
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [2]:
np.random.randint(0, 10, (4,5))

array([[6, 5, 6, 5, 8],
       [2, 1, 7, 9, 5],
       [0, 2, 0, 7, 4],
       [1, 8, 4, 8, 4]])

In [3]:
np.random.rand (4,4)

array([[0.07120242, 0.44472008, 0.36118384, 0.00237133],
       [0.77586153, 0.31581746, 0.19820107, 0.31858274],
       [0.26019491, 0.60518547, 0.92793534, 0.5700319 ],
       [0.05520441, 0.29008136, 0.52100686, 0.27013199]])

In [5]:
x1 = np.random.randint(0, 20, size = 6)

In [6]:
x1

array([ 4, 19,  6,  1,  4, 14])

In [7]:
x1[4]

4

In [16]:
# return giá trị đầu trong array:
x1[0]

4

In [17]:
# return giá trị cuối trong array:
x1[-1]

14

In [18]:
x1 [len(x1)-1]

14

In [20]:
x2 = np.random.randint(20, size = (3,4))

In [21]:
x2

array([[11,  7, 15, 18],
       [13, 17,  6,  4],
       [16, 15, 11, 16]])

In [22]:
x2 [1,2]

6

In [23]:
x2[1, 2] = 19

In [24]:
x2

array([[11,  7, 15, 18],
       [13, 17, 19,  4],
       [16, 15, 11, 16]])

In [25]:
x1

array([ 4, 19,  6,  1,  4, 14])

In [28]:
x1 [::2]

array([4, 6, 4])

In [29]:
x2

array([[11,  7, 15, 18],
       [13, 17, 19,  4],
       [16, 15, 11, 16]])

In [30]:
# Lấy 2 hàng đầu và 3 cột đầu tiên
x2 [:2, :3]

array([[11,  7, 15],
       [13, 17, 19]])

In [31]:
x2

array([[11,  7, 15, 18],
       [13, 17, 19,  4],
       [16, 15, 11, 16]])

In [34]:
# Lấy hết hai hàng đầu tiên và 2 cột đầu tiên
x2 [:,:2]

array([[11,  7],
       [13, 17],
       [16, 15]])

In [39]:
grid = np.arange (1,10)

In [40]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
grid.shape

(9,)

In [42]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x = np.array ([1, 2, 3])

In [44]:
x

array([1, 2, 3])

In [45]:
x.shape

(3,)

In [46]:
x.reshape((1,3))

array([[1, 2, 3]])

In [48]:
x.reshape((1,3)).shape

(1, 3)

In [49]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# Transpose
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [52]:
x = np.array ([1, 2, 3])
y = np.array ([3, 2, 1])

In [58]:
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [60]:
grid = np.array ([[1, 2, 3],[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [72]:
y = np.array ([[100],
               [100]])
grid = np.array ([[2, 4, 6], 
                  [3, 5, 7]])

In [74]:
np.hstack((grid, y))

array([[  2,   4,   6, 100],
       [  3,   5,   7, 100]])

In [75]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x1, x2, x3 = np.split(x, [0,5])

In [82]:
x1

array([], dtype=int32)

In [83]:
x2

array([1, 2, 3, 4, 5])

In [84]:
x3

array([6, 7, 8, 9])

In [85]:
a = np.arange(3)

In [86]:
a

array([0, 1, 2])

In [87]:
a+5 #Broadcasting

array([5, 6, 7])

In [89]:
b = np.ones((3,3))

In [90]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
a.shape, b.shape

((3,), (3, 3))

In [92]:
a+b #Broadcasting

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [93]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [94]:
c = np.arange(3).reshape((3,1))

In [95]:
c

array([[0],
       [1],
       [2]])

In [96]:
a

array([0, 1, 2])

In [97]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [2]:
list_number = [1, 2, 3]

In [3]:
ll = np.array(list_number)

In [4]:
ll

array([1, 2, 3])

In [5]:
sum(ll) # Python sum ()

6

In [6]:
np.sum(ll) # Numpy sum ()

6

In [7]:
# Create a massive numpy array
massive_array = np.random.random(10000)

In [8]:
massive_array [:5]

array([0.33460855, 0.25320716, 0.07778393, 0.15988573, 0.37933025])

In [9]:
massive_array.shape

(10000,)

In [10]:
%timeit sum(massive_array) # Python buil-in function sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

1.7 ms ± 45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
8.15 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
np.mean(np.array([1, 2, 3]))

2.0

In [12]:
np.mean(massive_array)

0.49624386076199956

In [13]:
np.max(np.array([1, 100, 999, 8888]))

8888

In [14]:
np.max(massive_array)

0.9999846590750932

In [15]:
np.min(np.array([1, 100, 999, 8888]))

1

In [16]:
np.min(massive_array)

5.289690317211715e-05

In [18]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)

# Standard Deviation (độ lệch chuẩn)
dog_height_std = np.std(dog_height)
print("standard deviation: ",dog_height_std)

#Variance (phương sai)
dog_height_variance = np.var(dog_height)
print("variance: ", dog_height_variance)

# Ngoài ra, độ lệch chuẩn còn được tính bằng căn bậc hai của phương sai
dog_height_std_1 = np.sqrt(dog_height_variance)
print("standard deviation using sqrt(var): ",dog_height_std_1)

standard deviation:  147.32277488562318
variance:  21704.0
standard deviation using sqrt(var):  147.32277488562318


In [3]:
x = np.array([1,2,33, 45, 98, 26, 47])
np.sort(x) 

array([ 1,  2, 26, 33, 45, 47, 98])

In [6]:
# A related function is argsort, which instead returns the indices of the sorted element
np.argsort(x)

array([0, 1, 5, 2, 3, 6, 4], dtype=int64)

In [14]:
np.random.seed(42)
MatA = np.random.randint(0, 10, (4,6))

In [15]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [18]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [19]:
A = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

In [20]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [21]:
# A(3x3) dot product B (3x2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [22]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [23]:
# B Transpose
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
(B.T)@A

array([[36, 48, 60],
       [24, 33, 42]])

In [27]:
# Number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size=(5,3))

In [28]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [29]:
# Creat weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [30]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [31]:
# Create a price array
prices = np.array([10, 8, 12])

In [32]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Prices"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [33]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [34]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [35]:
total_prices = weekly_sales @ butter_prices.T

In [36]:
total_prices

Prices
Mon       240
Tues      138
Wed       458
Thurs     232
Fri       142

In [37]:
weekly_sales["Total Prices"] =total_prices

In [38]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142